#!/bin/bash
set -e

. /usr/share/debconf/confmodule

CONFIG_FILE="/etc/asus-check-keyboard.cfg"

fallback_if_empty() {
    val="$1"
    fallback="$2"
    if [ -z "$val" ] || [ "$val" = "none" ]; then
        echo "$fallback"
    else
        echo "$val"
    fi
}
# Identifikace klávesnice
db_get asus-screen-toggle/usb_keyboard
SELECTED="$RET"
VENDOR_ID="0b05"
PRODUCT_ID="1bf2"
VENDOR_ID=$(echo "$SELECTED" | cut -d: -f1)
PRODUCT_ID=$(echo "$SELECTED" | cut -d: -f2 | cut -d' ' -f1)
echo "Zvoleno: VID=$VENDOR_ID, PID=$PRODUCT_ID AUX=$SELECTED"
# jméno displeje
db_get asus-screen-toggle/primary_display
PRIMARY_DISPLAY_NAME=$(fallback_if_empty "$RET" "eDP-1")
db_get asus-screen-toggle/secondary_display
SECONDARY_DISPLAY_NAME=$(fallback_if_empty "$RET" "eDP-2")
#jmeno vyka notebooku
db_get asus-screen-toggle/lid
LID=$(fallback_if_empty "$RET" "LID")

# Ověření, že nejsou stejné
if [ "$PRIMARY_DISPLAY_NAME" = "$SECONDARY_DISPLAY_NAME" ]; then
  echo "Upozornění: Primární a sekundární výstup jsou stejné ($PRIMARY)" >&2
fi

cat <<EOF > "$CONFIG_FILE"
VENDOR_ID="$VENDOR_ID"
PRODUCT_ID="$PRODUCT_ID"
PRIMARY_DISPLAY_NAME="$PRIMARY_DISPLAY_NAME"
SECONDARY_DISPLAY_NAME="$SECONDARY_DISPLAY_NAME"
LID="$LID"
EOF

AUTOSTART_FILE="/usr/share/asus-screen-toggle/autostart/asus-screen-toggle.desktop"

# Do /etc/skel
db_get asus-screen-toggle/autostart_system
if [ "$RET" = "true" ]; then
  mkdir -p /etc/xdg/autostart/
  cp -f "$AUTOSTART_FILE" /etc/xdg/autostart/
else
  # Do /etc/skel
  db_get asus-screen-toggle/autostart_skel
  if [ "$RET" = "true" ]; then
      mkdir -p /etc/skel/.config/autostart
      cp -f "$AUTOSTART_FILE" /etc/skel/.config/autostart/
  fi

  # Do existujících účtů
  db_get asus-screen-toggle/autostart_existing
  if [ "$RET" = "true" ]; then
      for userdir in /home/*; do
          [ -d "$userdir" ] || continue
          user=$(basename "$userdir")
          uid=$(id -u "$user" 2>/dev/null || echo 0)
          [ "$uid" -ge 1000 ] || continue

          su - "$user" -c "mkdir -p ~/.config/autostart"
          cp -f "$AUTOSTART_FILE" "$userdir/.config/autostart/"
          chown "$user:$user" "$userdir/.config/autostart/asus-screen-toggle.desktop"
      done
  fi
fi

/usr/bin/asus-check-keyboard-genrules.sh

/usr/bin/udevadm control --reload
/usr/bin/udevadm trigger

/usr/bin/systemctl enable asus-bottom-screen-init.service
/usr/bin/systemctl start asus-bottom-screen-init.service
