.TH ASUS-SCREEN-HELPER 1 "Prosinec 2025" "1.0.1" "Uživatelské příkazy"
.SH JMÉNO
asus-check-keyboard-system, asus-check-rotation \- Pomocné skripty Asus Screen Toggle
.SH POPIS
Tyto programy jsou vnitřní součástí balíčku
.B asus-screen-toggle
a jsou spouštěny automaticky systémem (udev, systemd) nebo agentem.
Běžný uživatel by je neměl spouštět ručně.
.SH VIZ TÉŽ
.BR asus-user-agent (1)
